### ISSUE TITLE
Import pydirectinput

### ISSUE THREAD

**Issue by Schwaab06** [TheRealChickon/ProjectMugetsuAutoMeditate#1]
hi 
i know you made this script in 20 mins after a late night but could you help me because when I try to run ''main.py'' it says 

''C:\Users\shane\Downloads\ProjectMugetsuAutoMeditate-main>main.py
Traceback (most recent call last):
  File "C:\Users\shane\Downloads\ProjectMugetsuAutoMeditate-main\main.py", line 13, in <module>
    import pydirectinput
ModuleNotFoundError: No module named 'pydirectinput' ''
i have install pydirectinput but it doesnt seem to be able to import it why is this?

**Comment by dizzymaxwell** [comment]
Simple question. Everything works fine until the end where it ask me to focus on the roblox tab. I can't seem to get it to realize that im focused on the roblox tab, any help?

**Comment by TheRealChickon** [comment]
Open cmd and do "pip install pydirectinput"
