### ISSUE TITLE
Not focusing on roblox

### ISSUE THREAD

**Issue by dizzymaxwell** [TheRealChickon/ProjectMugetsuAutoMeditate#2]
Everything works fine, until it ask me to focus on the roblox tab. It does not register as me focusing on the roblox tab so I can not get past it. Any help?

**Comment by TheRealChickon** [comment]
Can you show me what it prints?

**Comment by TheRealChickon** [comment]
I have updated the requirements.txt with the requirement.

**Comment by TheRealChickon** [comment]
Also what is the name of your roblox tab in the taskmanager?
