### ISSUE TITLE
PyAutoGUI not detecting PyScreeze and PyAutoGUI.ImageNotFoundException

### ISSUE THREAD

**Issue by Vyritaret** [TheRealChickon/ProjectMugetsuAutoMeditate#3]
[ProjectMugetsuAutoMeditate-1.2.2.zip](https://github.com/TheRealChickon/ProjectMugetsuAutoMeditate/files/15231177/ProjectMugetsuAutoMeditate-1.2.2.zip)
There was a few issues for me.

At first, PyAutoGui wasn't working with Pillow and couldn't detect PyScreeze, added an additional instruction since I'm too lazy to check for version of the updated PyAutoGui, which is just to update PyAutoGui.

After that, there was an error with PyAutoGui and the image detection, so I changed some basic lines where instead, it's Try and Except, whenever a line of code uses PyAutoGui over If and Else.

Might have not had any issues, but it wasn't working out for me so I decided to post this here with a potential fix for anyone interested! Happy Meditating!

**Comment by TheRealChickon** [comment]
I will read over the code and post it as 1.2.2 with credits if its fine. Im not going to test it - just going to check for malware etc.

**Comment by TheRealChickon** [comment]
Thanks , I will add this as the 1.2.2 Version with credits. I wasnt going to change or update things
- Info: I didnt test this, just checked for potentially malicious changes which it didnt contain it should work without issues from what I can see tho
